stages:
  data-prep:
    cmd: PYTHONPATH=. python src/data_prep.py
    deps:
      - src/data_prep.py
    outs:
      - data/raw/iris.csv

  train:
    cmd: PYTHONPATH=. python src/train.py
    deps:
      - data/raw/iris.csv
      - src/train.py
      - config/config.yaml
    outs:
      - models/model.joblib
