apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 4 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - |
              mlflow server \
              --host 0.0.0.0 \
              --port 5000 \
              --backend-store-uri {{ .Values.externalDatabase.type }}://{{ .Values.externalDatabase.user }}:{{ .Values.externalDatabase.password }}@{{ .Values.externalDatabase.host }}:{{ .Values.externalDatabase.port }}/{{ .Values.externalDatabase.database }} \
              --default-artifact-root {{ .Values.persistence.mountPath }}
          volumeMounts:
            - name: artifacts
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: {{ include "mlflow.fullname" . }}-artifacts
